env:
  es2021: true
  browser: true,
extends: airbnb-base
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: {
  import/extensions: [error, ignorePackages],
  no-param-reassign: off,
}
